### ISSUE TITLE
USER STORY: Project board

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#1]
EPIC: Project setup

As a **developer** I can **set up a project board** so that **I can plan my project**.

## Acceptance Criteria
* Acceptance Criteria 1: project board is ready

## Tasks
- [x]  Task 1: Create project board
- [x]  Task 2: Create issues, labels, epics and milestones for back end project
- [x]  Task 3: Create issues, labels, epics and milestones for front end project
