### ISSUE TITLE
USER STORY: Artwork model

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#12]
EPIC: Artwork functionality

As a **developer**, I can **create the Artwork model for the api** so that **I can create functionality for storing artwork related data.**

## Acceptance Criteria
* Acceptance Criteria 1: Artwork app created in the workspace
* Acceptance Criteria 2: All related files are updated
* Acceptance Criteria 3: Model migrated to the database

## Tasks
- [x] Task 1: Write a model for the Artwork app
- [x] Task 2: Write serializer for the Artwork model
- [x] Task 3: Write serializer permissions for the Artwork model
- [x] Task 4: Write urls for the Artwork model
- [x] Task 5: Write views for the Artwork model
- [x] Task 6: Migrate to database
