### ISSUE TITLE
USER STORY: Bid model

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#13]
EPIC: Bid functionality

As a **developer**, I can **create the Bid model for the api** so that **I can create functionality for storing bid related data.**

## Acceptance Criteria
* Acceptance Criteria 1: Bid app created in the workspace
* Acceptance Criteria 2: All related files are updated
* Acceptance Criteria 3: Model migrated to the database

## Tasks
- [x] Task 1: Write a model for the Bid app
- [x] Task 2: Write serializer for the Bid model
- [x] Task 3: Write serializer permissions for the Bid model
- [x] Task 4: Write urls for the Bid model
- [x] Task 5: Write views for the Bid model
- [x] Task 6: Migrate to database
