### ISSUE TITLE
USER STORY: Profile model

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#14]
EPIC: Profile functionality

As a **developer**, I can **create the Profile model for the api** so that **I can create functionality for storing profile related data.**

## Acceptance Criteria
* Acceptance Criteria 1: Profile app created in the workspace
* Acceptance Criteria 2: All related files are updated
* Acceptance Criteria 3: Model migrated to the database

## Tasks
- [x] Task 1: Write a model for the Profile app
- [x] Task 2: Write serializer for the Profile model
- [x] Task 3: Write serializer permissions for the Profile model
- [x] Task 3: Write urls for the Profile model
- [x] Task 4: Write views for the Profile model
- [x] Task 5: Migrate to database
