### ISSUE TITLE
USER STORY: Save model

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#15]
EPIC: Save functionality

As a **developer**, I can **create the Save model for the api** so that **I can create functionality for storing save model related data.**

## Acceptance Criteria
* Acceptance Criteria 1: Save app created in the workspace
* Acceptance Criteria 2: All related files are updated
* Acceptance Criteria 3: Model migrated to the database

## Tasks
- [x] Task 1: Write a model for the Save app
- [x] Task 2: Write serializer for the Save model
- [x] Task 3: Write serializer permissions for the Save model
- [x] Task 4: Write urls for the Save model
- [x] Task 5: Write views for the Save model
- [x] Task 6: Migrate to database
