### ISSUE TITLE
USER STORY: Contact model

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#16]
EPIC: Contact functionality

As a **developer**, I can **create the Contact model for the api** so that **I can create functionality for storing Contact model related data.**

## Acceptance Criteria
* Acceptance Criteria 1: Contact app created in the workspace
* Acceptance Criteria 2: All related files are updated
* Acceptance Criteria 3: Model migrated to the database

## Tasks
- [ ] Task 1: Write a model for the Contact app
- [ ] Task 2: Write serializer for the Contact model
- [ ] Task 3: Write serializer permissions for the Contact model
- [ ] Task 3: Write urls for the Contact model
- [ ] Task 4: Write views for the Contact model
- [ ] Task 5: Migrate to database
