### ISSUE TITLE
USER STORY: New back-end workspace

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#2]
EPIC: Project setup

As a **developer** I can **set up a new workspace for back-end** so that **I can start working on my project.**

## Acceptance Criteria
* Acceptance Criteria 1: a repository is in Github
* Acceptance Criteria 2: an IDE to work in
* Acceptance Criteria 3: readme and testing files

## Tasks
- [x]  Task 1: Create a github repository with initial README and TESTING files
- [x]  Task 2: Set up env.py in Gitpod
- [x]  Task 3: Set up secret keys in the env.py
- [x]  Task 4: Install Django REST Framework
