### ISSUE TITLE
USER STORY: Set up Cloudinary

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#4]
EPIC: Project setup

As a **developer** I can **set up Cloudinary** so that **any uploaded image can be stored in cloud storage.**

## Acceptance Criteria
- Acceptance Criteria 1: Download Cloundinary and update settings.py
- Acceptance Criteria 2: check image upload functionality.

## Tasks
- [x]  Task 1: Download Cloundinary
- [x]  Task 2: Save the api key in env.py
- [x]  Task 3: Update settings.py
- [x]  Task 4: Update requirements.txt file
