### ISSUE TITLE
USER STORY: Set up JWT tokens

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#6]
EPIC: User authentication

As a **developer** I can **set up JWT tokens** so that **the user doesn’t need to log in repeatedly during one single session.**

## Acceptance Criteria
- Acceptance Criteria 1: JWT tokens set up
- Acceptance Criteria 2: user’s login session is verified

## Tasks
- [x]  Task 1: install django rest auth
- [x]  Task 2: install JWT tokens
- [x]  Task 3: update setttings.py & urls.py files
- [x]  Task 4: migrate changes
