### ISSUE TITLE
USER STORY: Back-end README

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#7]
EPIC: Documentation 

As a **developer**, I can n**ote the website progression in the back-end README** so that **anyone can see the steps and actions taken for the release of the website.**

## Acceptance Criteria
- Acceptance Criteria 1: Readme file is updated throughout the progression of the project
- Acceptance Criteria 2: TESTING.md file is updated with any changes and major bugs

## Tasks
- [x]  Task 1: Record project scope and technologies used in the README.md
- [x]  Task 2: Record any resources and tools used for testing, validation and deployment
- [x]  Task 3: Have a section about deployment, cloning and forking the repository
- [x]  Task 4: Include the deployed site’s website in the README.md
- [x]  Task 5: Proofread
