### ISSUE TITLE
USER STORY: Deploy back-end repository

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly-api#8]
EPIC: Deployment

As a **developer** I can **deploy the back-end repository to Heroku** so that it is **accessible online**.

## Acceptance Criteria
- Acceptance Criteria 1: Environment variables are configured and hidden
- Acceptance Criteria 2: All settings and requirements configured
- Acceptance Criteria 3: The project is deployed
- 
## Tasks
- [x]  Task 1: Install all needed dependencies
- [x]  Task 2: Freeze requirements
- [x]  Task 3: Add CORS settings
- [x]  Task 4: Create Procfile
- [x]  Task 5: Push the project to Github repository
- [x]  Task 6: Deploy to Heroku
- [x]  Task 7: Check the deployed back-end app is working
